---

- name: Copy emulation.md to host
  win_copy:
    src: "emulation.md"
    dest: 'C:\emulation.md'

- name: Give everyone access to emulation.md
  win_shell: "icacls C:\\emulation.md /grant Users:F"
  register: win_shell_output
  retries: 5
  delay: 300
  until: win_shell_output.stderr == ""

- debug:
    var: win_shell_output
