---

- name: Copy setup privesc script to host
  win_copy:
    src: "setup_privesc.ps1"
    dest: 'C:\temp\setup_privesc.ps1'

- name: Run setup privesc
  win_shell: "C:\\temp\\setup_privesc.ps1 {{ ansible_user }} {{ general.attack_range_password }}"
  register: win_shell_output
  retries: 5
  delay: 300
  until: win_shell_output.stderr == ""

- debug:
    var: win_shell_output
